### ISSUE TITLE
Recieve a traceback error when component is installed 0.92.1

### ISSUE THREAD

**Issue by sinker1345** [hunterjm/hassio-addons#46]
traceback error is as follows

```
Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/requirements.py", line 80, in loadable
    req = pkg_resources.Requirement.parse(package)
  File "/srv/homeassistant/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3095, in parse
    req, = parse_requirements(s)
ValueError: not enough values to unpack (expected 1, got 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/helpers/entity_component.py", line 204, in _async_setup_platform
    self.hass, self.config, self.domain, platform_type)
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/setup.py", line 222, in async_prepare_setup_platform
    await async_process_deps_reqs(hass, hass_config, integration)
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/setup.py", line 281, in async_process_deps_reqs
    hass, integration.domain, integration.requirements)):
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/requirements.py", line 40, in async_process_requirements
    if await pkg_cache.loadable(req):
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/requirements.py", line 84, in loadable
    req = pkg_resources.Requirement.parse(urlparse(package).fragment)
  File "/srv/homeassistant/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3095, in parse
    req, = parse_requirements(s)
ValueError: not enough values to unpack (expected 1, got 0)
```

I get this error when the xbox custom_component is installed and when I remove the custom component the error goes away. other than the error the platform appears to start normally however there is no media player device even though I have added it into my config.yaml.

I have made sure the rest server is authenticated and an XBOX one is found on the same subnet as HA.

Any help would be appreciated as the hass --check config option for HA appears to return no errors. I am installed on an Ubuntu VM running in VENV mode.

**Comment by sinker1345** [comment]
this issue has been resolved, was using the following manifest.json which contained empty quotes in requirements
```
{
  "domain": "xboxone",
  "name": "XboxOne",
  "documentation": "https://github.com/hunterjm/hassio-addons/tree/master/xboxone",
  "requirements": [
    ""
  ],
  "dependencies": [],
  "codeowners": []
}
```

removing qutoes and formatting requirements as follows solved the issue
```
"requirements": [],
```
